// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phhgipxqyxiczhbqrisu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoaGdpcHhxeXhpY3poYnFyaXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDgyNDYsImV4cCI6MjA3MTM4NDI0Nn0.Z_fG5U9O5fnBjZZzlwONL6vVDKVRXxxp1VJTL9-YULk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});